const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('bestScore'),levelEl=document.getElementById('level'),statusEl=document.getElementById('status'),startScreen=document.getElementById('startScreen'),gameOverScreen=document.getElementById('gameOverScreen'),finalScoreEl=document.getElementById('finalScore');
const WIDTH=900,HEIGHT=560,PANEL_W=450,playerSize=28;let score=0,best=Number(localStorage.getItem('dodge-dual-best')||0),running=false,lastTime=0,elapsed=0,leftSpawn=0,rightSpawn=0,leftPressed=false,rightPressed=false,upPressed=false,downPressed=false,leftBlocks=[],rightBlocks=[];const leftPlayer={x:211,y:HEIGHT-58},rightPlayer={x:WIDTH-playerSize-26,y:HEIGHT/2-playerSize/2};bestEl.textContent=best;
function panelBackground(x,accent){ctx.fillStyle='#101827';ctx.fillRect(x,0,PANEL_W,HEIGHT);ctx.strokeStyle=accent;ctx.globalAlpha=.08;for(let gx=x;gx<=x+PANEL_W;gx+=36){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,HEIGHT);ctx.stroke()}for(let gy=0;gy<=HEIGHT;gy+=36){ctx.beginPath();ctx.moveTo(x,gy);ctx.lineTo(x+PANEL_W,gy);ctx.stroke()}ctx.globalAlpha=1}
function drawPlayer(p,accent){ctx.save();ctx.shadowColor=accent;ctx.shadowBlur=18;ctx.fillStyle=accent;ctx.fillRect(p.x,p.y,playerSize,playerSize);ctx.shadowBlur=0;ctx.fillStyle='#e2f8ff';ctx.fillRect(p.x+7,p.y+7,6,6);ctx.restore()}
function drawBlock(b){ctx.save();ctx.shadowColor='#fa5d70';ctx.shadowBlur=13;ctx.fillStyle='#fa5d70';ctx.fillRect(b.x,b.y,b.size,b.size);ctx.shadowBlur=0;ctx.fillStyle='#ffacb7';ctx.fillRect(b.x+b.size*.22,b.y+b.size*.22,b.size*.16,b.size*.16);ctx.restore()}
function drawLabels(){ctx.fillStyle='rgba(241,244,247,.7)';ctx.font='500 11px DM Mono, monospace';ctx.fillText('LEFT / ← →',22,28);ctx.fillStyle='rgba(84,200,245,.7)';ctx.fillText('RIGHT / ↑ ↓',PANEL_W+22,28);ctx.strokeStyle='#30394c';ctx.beginPath();ctx.moveTo(PANEL_W,0);ctx.lineTo(PANEL_W,HEIGHT);ctx.stroke()}
function render(){panelBackground(0,'#d5e84b');panelBackground(PANEL_W,'#54c8f5');leftBlocks.forEach(drawBlock);rightBlocks.forEach(drawBlock);if(running){drawPlayer(leftPlayer,'#d5e84b');drawPlayer(rightPlayer,'#54c8f5')}drawLabels()}
function setScore(v){score=v;scoreEl.textContent=score;levelEl.textContent=String(Math.min(99,Math.floor(elapsed/8)+1)).padStart(2,'0')}
function spawnLeft(){const size=22+Math.random()*25;leftBlocks.push({x:12+Math.random()*(PANEL_W-size-24),y:-size,size,speed:120+elapsed*7+Math.random()*35})}
function spawnRight(){const size=22+Math.random()*25;rightBlocks.push({x:PANEL_W-size,y:45+Math.random()*(HEIGHT-size-70),size,speed:125+elapsed*7.5+Math.random()*35})}
function hit(a,b){return a.x<b.x+b.size&&a.x+playerSize>b.x&&a.y<b.y+b.size&&a.y+playerSize>b.y}
function startGame(){if(running)return;running=true;score=0;elapsed=0;leftSpawn=0;rightSpawn=0;leftBlocks=[];rightBlocks=[];leftPlayer.x=PANEL_W/2-playerSize/2;leftPlayer.y=HEIGHT-playerSize-26;rightPlayer.x=WIDTH-playerSize-26;rightPlayer.y=HEIGHT/2-playerSize/2;setScore(0);startScreen.classList.add('hidden');gameOverScreen.classList.add('hidden');statusEl.textContent='同时看住两个屏幕';canvas.focus();lastTime=performance.now();requestAnimationFrame(loop)}
function endGame(){running=false;finalScoreEl.textContent=score;gameOverScreen.classList.remove('hidden');statusEl.textContent='按 R 或空格重新开始';document.querySelector('.game-shell').classList.add('shake');setTimeout(()=>document.querySelector('.game-shell').classList.remove('shake'),260);if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('dodge-dual-best',best)}render()}
function loop(now){if(!running)return;const dt=Math.min((now-lastTime)/1000,.04);lastTime=now;elapsed+=dt;const move=250*dt;leftPlayer.x+=(Number(rightPressed)-Number(leftPressed))*move;leftPlayer.x=Math.max(10,Math.min(PANEL_W-playerSize-10,leftPlayer.x));rightPlayer.y+=(Number(downPressed)-Number(upPressed))*move;rightPlayer.y=Math.max(42,Math.min(HEIGHT-playerSize-12,rightPlayer.y));leftSpawn+=dt*1000;rightSpawn+=dt*1000;const interval=Math.max(300,1050-elapsed*32);if(leftSpawn>=interval){leftSpawn=0;spawnLeft()}if(rightSpawn>=interval*1.08){rightSpawn=0;spawnRight()}let next=[];for(const b of leftBlocks){b.y+=b.speed*dt;if(hit(leftPlayer,b)){endGame();return}if(b.y>HEIGHT)setScore(score+1);else next.push(b)}leftBlocks=next;next=[];for(const b of rightBlocks){b.x+=b.speed*dt;if(hit(rightPlayer,b)){endGame();return}if(b.x>PANEL_W*2)setScore(score+1);else next.push(b)}rightBlocks=next;render();requestAnimationFrame(loop)}
function press(key,v){if(key==='left')leftPressed=v;if(key==='right')rightPressed=v;if(key==='up')upPressed=v;if(key==='down')downPressed=v}function bind(id,key){const b=document.getElementById(id);['pointerdown','touchstart'].forEach(e=>b.addEventListener(e,x=>{x.preventDefault();press(key,true)}));['pointerup','pointerleave','pointercancel','touchend'].forEach(e=>b.addEventListener(e,x=>{x.preventDefault();press(key,false)}))}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')leftPressed=true;if(e.key==='ArrowRight')rightPressed=true;if(e.key==='ArrowUp')upPressed=true;if(e.key==='ArrowDown')downPressed=true;if(e.key===' '||e.key.toLowerCase()==='r')startGame()});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft')leftPressed=false;if(e.key==='ArrowRight')rightPressed=false;if(e.key==='ArrowUp')upPressed=false;if(e.key==='ArrowDown')downPressed=false});document.getElementById('startButton').addEventListener('click',startGame);document.getElementById('restartButton').addEventListener('click',startGame);bind('leftButton','left');bind('rightButton','right');bind('upButton','up');bind('downButton','down');render();
